### ISSUE TITLE
Display local artwork/fanart

### ISSUE THREAD

**Issue by fabioneves** [cguZZman/plugin.googledrive#133] opened 2020-03-27 10:26 UTC
Hello,

Is it possible to display Kodi local fanart in a folder?
If not possible to display when browsing addon folders, could it be possible to export local fanart together with the strm files?

I have local artwork as per Kodi instructions: https://kodi.wiki/view/Movie_artwork in my google folders, but none of them are exported, in this case I basically have "Movie Name (year)-poster.jpg".

I basically won't index this folder in Kodi library since it's local content and it would be cool to show a poster when browsing the strm files.

Thanks!

**Comment by cguZZman** [comment] 2020-04-23 16:54
This sounds like a duplicate of #107 or #106. Will be in the list for a future enhancement.

**Comment by cguZZman** [comment] 2020-10-11 02:12
fixed in last version

**Closed** 2020-10-11 02:15 UTC
Labels: enhancement
