### ISSUE TITLE
ERROR: CCurlFile::FileBuffer - Failed: HTTP returned error 401

### ISSUE THREAD

**Issue by Abu3safeer** [cguZZman/plugin.googledrive#190] opened 2020-10-14 02:01 UTC
**Describe the bug**
When watching any video, almost after about at 30 minutes, it randomly crashes and close the player, like when you click on pause, no error messages, just close the player.

This issue is on Nvidia Shield, details in screenshot section below.

**To Reproduce**
1. watch any video from google drive
2. after random period of time it crashes.

**Your debug log file**
kodi.log: https://textbin.net/30TteRPRyt
kodi.old.log: https://textbin.net/ehRk8X9RQV

**Screenshots**
![image](https://user-images.githubusercontent.com/12091003/95934416-76600280-0dd9-11eb-9c71-0510f5d2f834.png)
![image](https://user-images.githubusercontent.com/12091003/95934440-7e1fa700-0dd9-11eb-97e3-3e7405f863a5.png)
![image](https://user-images.githubusercontent.com/12091003/95934447-81b32e00-0dd9-11eb-8456-c15cf8d286d9.png)
![image](https://user-images.githubusercontent.com/12091003/95934453-8546b500-0dd9-11eb-93f8-1f16b953409d.png)
![image](https://user-images.githubusercontent.com/12091003/95934466-8aa3ff80-0dd9-11eb-9931-729fde52c1c8.png)

**Comment by cguZZman** [comment] 2020-10-14 13:04
Your screenshot says Kodi version 18.8 but your logs are for version 17.6. Please double check you are attaching the correct log files.
Also, looks like your log file was modified since the list of addons and versions are not listed. I just need to see the version of the addon you are ussing. 
Anyway, I was able to see you are using an old version from a request. 
Try again installing the latest version from my repo and also enable the verbose logging for the **libcURL** library. Need to see what is that 401 error about.

**Comment by Abu3safeer** [comment] 2020-10-14 15:33
Thank you for the detailed explanation, I will update you when I do what you say.

**Comment by Abu3safeer** [comment] 2020-10-15 01:49
New fresh log with verbose enabled (I wish it is enabled correctly)
https://textbin.net/9Wkqg7VPjO

This is addon version
![image](https://user-images.githubusercontent.com/12091003/96067180-d4f0b380-0ea1-11eb-90a6-7acc1dad7013.png)

**Comment by cguZZman** [comment] 2020-10-19 22:02
Okay, in short, this is an issue caused by the update that google made to the drive api. Kind of the same reason the source mode is not working anymore. Your auth token with google expires after 1 hour, and kodi is trying to use the same even after that period of time.
It is strange anyway, because the download of the video should happen fast enough to avoid the 401 error. Is this happening when you seek or change your video progress?
Anyway, the workaround would be to just play your video again.
Kodi should not crash in any case tho. So, if it is happening, I would suggest you to report that crash to team kodi.

Will close this issue since there is nothing else from the addon to do for now.

**Closed by cguZZman** 2020-10-19 22:02 UTC
Labels: waiting for info

**Comment by Abu3safeer** [comment] 2020-10-19 22:25
It happens on seek, I do nothing, run a movie and watch, after some period of time the player closes like I click on the square button (Stop button)
I use other apps like nPlayer and they work with no issue though it was not updated for years (android version.
