### ISSUE TITLE
folder monitoring creates .mkv files, not .mkv.strm.  This causes Kodi to not play the files

### ISSUE THREAD

**Issue by klyco** [cguZZman/plugin.googledrive#139] opened 2020-04-08 17:40 UTC
**Describe the bug**
It seem sthat my Google Drive is creating the files while monitoring my videos folder, however, when it creates the files, it creates a videoname.mkv file, not videoname.mkv.strm file.

This causes an issue for Kodi when I try to play the file from the Library, as it is expecting an MKV file.

<img width="518" alt="Capture" src="https://user-images.githubusercontent.com/19582491/78815621-5a405c00-7985-11ea-9e0e-b346694edc33.PNG">

**Screenshots**

**Comment by klyco** [comment] 2020-04-08 18:23
To add to this, If I then run a full export, it correctly creates the .mkv.strm files, but leaves the .mkv files in the directory, so now Kodi sees multiple files in the library.

Then, if I leave it running, and ad more files, the folder monitor will work correctly for the first few files (i.e. it will create .mkv.strm) but then after a random time interval, it will start creating .mkv files again.

**Comment by vankdj** [comment] 2020-04-10 12:07
Yes, some friends and I are the same.  We did not find a solution ... We have done a clean installation and we get the same result.
Sorry for my bad english.

**Comment by fandangos** [comment] 2020-04-11 17:08
I came here to create a bug report exactly on this. 

Hoping for a solution too.

**Comment by klyco** [comment] 2020-04-15 00:24
Aha!  I have found out how I can reliably recreate the issue.  It seems that when I delete a file in my google drive, rather than deleting the .strm file, the app changes it to .mkv!

**Comment by fandangos** [comment] 2020-04-15 13:10
It's not that, I have folders that are not monitored and I haven't touched that gets this kind of behavior. 

For me the only solution so far is go into the folder via CMD (or bash in linux) and do:
ren /S *.mkv *.mkv.strm
This will change back all mkv files to .mkv.strm if the file already exist it will fail so I do:
del /S *.mkv

But if you still need watch folder this is broken for now. 
I would say the best deal would be getting a raspberry pi4 (if you don't already have a server/NAS in your house) and mount the google drive with rclone. Or use rclone with fuse on Windows. 
It's the only solution that will work 100% for now.

**Comment by cguZZman** [comment] 2020-04-15 13:44
Yet nobody has posted a debug log file. The issue template is there for a reason.

**Comment by klyco** [comment] 2020-04-15 20:46
@cguZZman - my sincere apologies!
It seems, although I can recreate the issue, it sees to be intermittent still; i.e. not every file I delete will turn into a .mkv file.  I am now running 2 devices in debug mode, waiting for the issue to happen again.  As soon as it does, i will upload the debug log.  Thx!

**Comment by klyco** [comment] 2020-04-16 00:25
OK so I got it in the log!
https://pastebin.com/pakhuUJ3

**Comment by klyco** [comment] 2020-04-16 00:32
Another
https://pastebin.com/1bAzwDgF
The file that was created (or changed) to .mkv was S45E08 $50,000 Champs Challenge: Grand Finale.mkv

**Comment by klyco** [comment] 2020-04-16 00:34
And one final one.
https://pastebin.com/DknCKKYd

Sorry my pastebin is the free one and only lets me paste 512k

**Comment by klyco** [comment] 2020-04-16 00:35
https://pastebin.com/iNU8EGv7

**Comment by vankdj** [comment] 2020-04-16 17:23
My kodilog: https://www.dropbox.com/s/edy1rf8bmhsl0q9/kodilog.zip?dl=0

![Screenshot_2020-04-16-19-15-35-744_com mixplorer](https://user-images.githubusercontent.com/48133143/79486840-94f66400-8017-11ea-802f-e693c7b3061e.jpg)

Some films with error ☝️

Sorry for my bad english

**Comment by klyco** [comment] 2020-04-21 20:48
Please let us know if these error logs are helpful or should we post more?  Thx!

**Comment by rodneyshupe** [comment] 2020-04-23 05:45
@cguZZman  @christopher2505 @xybydy could this be related to changes made as part of [this pull request](https://github.com/cguZZman/script.module.clouddrive.common/pull/11), timing of some of the first reports seem to coincide.

**Comment by xybydy** [comment] 2020-04-23 11:37
Okay, I could not reproduce the error but found and fixed some points.  Made a pull request on [](https://github.com/cguZZman/script.module.clouddrive.common/pull/13)

Could you guys please update your `script.module.clouddrive.common`  from my fork and test.

**Comment by klyco** [comment] 2020-04-23 16:33
OK I updated the file and it looks like it works!  I can't seem to recreate the issue now.  I'll monitor for a few days and let you know.

**Comment by rodneyshupe** [comment] 2020-04-23 20:36
Second anecdotal result here after updating the export.py from the pull request.  Seems to have fixed the issue.

**Comment by cguZZman** [comment] 2020-04-23 22:18
Code fix was merged with version 1.3.6 for the google addon and 1.2.15 for the common drive module.
Will send it to kodi repository soon.

**Closed by cguZZman** 2020-04-23 22:18 UTC
Labels: debug log required

**Comment by klyco** [comment] 2020-04-23 22:25
Thanks SO much Carlos!

**Comment by cguZZman** [comment] 2020-04-23 22:27
thanks to @xybydy for taking care of this.

**Comment by klyco** [comment] 2020-04-24 17:37
Sorry, yes HUGE thanks to  @xybydy  for this!

**Comment by klyco** [comment] 2020-04-25 03:33
Oops!  Looks like it happened again.  I'll try to get a debug log...

**Comment by fandangos** [comment] 2020-04-25 11:35
Here it seemed to have solved the problem. Still something weird is happening with this update. I used to be able to see "my exports" on my team drives. Now I can save an export and it monitors the designated folder but I can't see a list of exports for my Team Drives anymore, only for my own drive.

**Comment by xybydy** [comment] 2020-04-25 18:09
@fandangos that's just a coincidence. the modified part is totally unrelated to your problem.

**Comment by klyco** [comment] 2020-05-06 17:04
OK I have captured a log with the same issue happening.
./videos/TvShows/Chopped (2009)/Season 45/S45E20 Beat the Judge Amanda.mkv
./videos/TvShows/Chopped (2009)/Season 45/S45E19 Beat the Judge Tiffani.mkv
When the files were renamed and moved to a new folder (moved from Season 46 to Season 45) they were recreated as .mkv
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/4588240/kodi.log)

Do we need to open a new case, or can we re-open this one?
