### ISSUE TITLE
Don't add account in Kodi nexus.

### ISSUE THREAD

**Issue by luhanmcs** [cguZZman/plugin.googledrive#302] opened 2022-11-16 16:34 UTC
I try with version 1.4.11 and 1.4.10-matrix and don't add account get error.

![Screenshot_20221116-132930](https://user-images.githubusercontent.com/22850716/202238342-2ba3e684-3017-4535-b3c8-19974c35321c.png)

Log:

[plugin.googledrive][MainThread-2217994608]: [plugin.googledrive] [1.4.10+matrix.2]/[1.3.9+matrix.2]
                                                   
                                                   Erro desconhecido:
                                                   module 'inspect' has no attribute 'getargspec'
                                                   Por favor, tente novamente.
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py", line 702, in route
                                                       for name in inspect.getargspec(method)[0]:
                                                                   ^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'inspect' has no attribute 'getargspec'
                                                   
                                                   
                                                   show_error_dialog: True

**Comment by billol25** [comment] 2022-11-26 19:21
I can reply the error with last nightly version of KODI 20,  error opening media with previous account, rolling back to KODI 20 beta1. With KODI 20 beta1 same error, rolling back to Alpha 3. Ok with Kodi 20 alpha 3.

**Comment by adarshvadwitiya** [comment] 2022-12-12 10:22
Also happening with Android TV on Kodi 20-RC-1

**Comment by PaulinHalenria** [comment] 2022-12-20 22:08
Got the same error, don't find anything when googling it except this thread

**Comment by RedSquirrel87** [comment] 2022-12-25 17:54
Same here with Kodi 20 rc2, I solved this issue by simply editing the file at:
`.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py` 
by changing the _getargspec_ with the new _getfullargspec_, so that at line 702:
`for name in inspect.getargspec(method)[0]:`
become 
`for name in inspect.getfullargspec(method)[0]:`
and also this Google Drive extension came back to work.

**Comment by RobElse1992** [comment] 2022-12-26 09:57
Any ideas how we can do RedSquirrels fix on Android TV? Access to files is very limited on Android 12, I can't seem to find anything using Kodis built in file browser

**Comment by RedSquirrel87** [comment] 2022-12-26 11:02
> Any ideas how we can do RedSquirrels fix on Android TV? Access to files is very limited on Android 12, I can't seem to find anything using Kodis built in file browser

On a PC you could edit that line in the source code of the clouddrive module, pack it in a ZIP package, move it on the device and then install it with the "install from a ZIP file" feature of Kodi replacing the installed one.
Anyway I just created a pull request, maybe it will be fixed soon in the official repository too

**Comment by adarshvadwitiya** [comment] 2022-12-28 18:20
> Same here with Kodi 20 rc2, I solved this issue by simply editing the file at:
> `.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py`
> by changing the _getargspec_ with the new _getfullargspec_, so that at line 702:
> `for name in inspect.getargspec(method)[0]:`
> become
> `for name in inspect.getfullargspec(method)[0]:`
> and also this Google Drive extension came back to work.

Cheers mate! This is working

**Comment by makykiki** [comment] 2022-12-28 21:37
Very thanks RedSquirrel87 this works perfectly.

**Comment by ClassickTech** [comment] 2023-01-18 04:39
> Same here with Kodi 20 rc2, I solved this issue by simply editing the file at: `.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py` by changing the _getargspec_ with the new _getfullargspec_, so that at line 702: `for name in inspect.getargspec(method)[0]:` become `for name in inspect.getfullargspec(method)[0]:` and also this Google Drive extension came back to work.

Where exactly would I find this in the source code? Also, your zip is not working for me or 20 Nexus stable.

**Comment by JohnJohn45** [comment] 2023-01-18 06:16
Thanks you for the tip. I will test modify zip addon directly and install it on my Android tv.

**Comment by JohnJohn45** [comment] 2023-01-18 06:17
> > Same here with Kodi 20 rc2, I solved this issue by simply editing the file at: `.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py` by changing the _getargspec_ with the new _getfullargspec_, so that at line 702: `for name in inspect.getargspec(method)[0]:` become `for name in inspect.getfullargspec(method)[0]:` and also this Google Drive extension came back to work.
> 
> Where exactly would I find this in the source code? Also, your zip is not working for me or 20 Nexus stable.

Addon is here : https://mirrors.kodi.tv/addons/nexus/script.module.clouddrive.common/

You can edit addon.py file in the zip and install it

**Comment by janglapuk** [comment] 2023-01-18 15:09
Haven't been able to try it, but this should solve the problem. Need someone to do the PR.

```python
if not hasattr(inspect, 'getargspec'):
    inspect.getargspec = inspect.getfullargspec
```

The solution is taken from this comment:
https://github.com/pyinvoke/invoke/issues/833#issuecomment-1293148106

**Comment by ClassickTech** [comment] 2023-01-19 02:29
> Haven't been able to try it, but this should solve the problem. Need someone to do the PR.
> 
> ```python
> if not hasattr(inspect, 'getargspec'):
>     inspect.getargspec = inspect.getfullargspec
> ```
> 
> The solution is taken from this comment: [pyinvoke/invoke#833 (comment)](https://github.com/pyinvoke/invoke/issues/833#issuecomment-1293148106)

Where do you change this at?

**Comment by ClassickTech** [comment] 2023-01-19 02:30
> > > Same here with Kodi 20 rc2, I solved this issue by simply editing the file at: `.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py` by changing the _getargspec_ with the new _getfullargspec_, so that at line 702: `for name in inspect.getargspec(method)[0]:` become `for name in inspect.getfullargspec(method)[0]:` and also this Google Drive extension came back to work.
> > 
> > 
> > Where exactly would I find this in the source code? Also, your zip is not working for me or 20 Nexus stable.
> 
> Addon is here : https://mirrors.kodi.tv/addons/nexus/script.module.clouddrive.common/
> 
> You can edit addon.py file in the zip and install it

I changed to getfullargspec and zipped. Add on still gives me error when trying to install by zip on Kodi 20

**Comment by I-MacHunt** [comment] 2023-01-19 16:10
> 

I can't get the files transferred to my Nvidia Shield as for some reason it will only copy the folders but not their contents.

**Comment by barclayslb** [comment] 2023-01-19 20:42
> > Same here with Kodi 20 rc2, I solved this issue by simply editing the file at:
> > `.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py`
> > by changing the _getargspec_ with the new _getfullargspec_, so that at line 702:
> > `for name in inspect.getargspec(method)[0]:`
> > become
> > `for name in inspect.getfullargspec(method)[0]:`
> > and also this Google Drive extension came back to work.
> 
> Cheers mate! This is working

thank you, that solve the problem !

**Comment by janglapuk** [comment] 2023-01-20 16:05
Officialy, this issue already fixed from related repos. Look at the merged PRs:

- https://github.com/cguZZman/plugin.googledrive/commit/61faecc3348972b30698167d47354b23d4fd2b37
- https://github.com/cguZZman/script.module.clouddrive.common/commit/10bad39ff0c52cee1cab074b20b635a92a066841
- https://github.com/cguZZman/script.module.clouddrive.common/commit/c9a5f714819b42230bad8480324036c517d58ca3

The current problem is the addon hasn't been officially released yet at [repository.plugins](https://github.com/cguZZman/repository.plugins) for Nexus updates, you will not get updates on Kodi until @cguZZman  updates it.

Someone has already opened an issue (https://github.com/cguZZman/repository.plugins/issues/17) regarding this problem, we hope @cguZZman will make a release soon.

Just wait for an official update or create your own ZIP.

**Comment by I-MacHunt** [comment] 2023-01-20 16:13
The problem is that I can't transfer any files to my Nvidia Shield, so even if I could create a zip file, I can't access it.

**Comment by janglapuk** [comment] 2023-01-20 16:32
> The problem is that I can't transfer any files to my Nvidia Shield, so even if I could create a zip file, I can't access it.

If you can't wait for the release,
1. Create or fork @cguZZman [repository.plugins](https://github.com/cguZZman/repository.plugins) as your own addon repository. 
2. Update the necessary XMLs, ZIPs, hashes, and so on with the latest. 
3. Upload to your web server and add the URL as custom repo source in your Kodi.

I don't know how to make this easy.

**Comment by I-MacHunt** [comment] 2023-01-20 16:42
Thanks, I'll try that.

**Comment by vician** [comment] 2023-01-20 16:53
You can use mine temporary fix zip on https://wiki.vician.net/tv.zip but you need to enable unknown sources and overriding system packages updates from unknown sources. And you would need to uninstall and remove it when the official update will be released.

**Comment by janglapuk** [comment] 2023-01-21 10:02
> You can use mine temporary fix zip on https://wiki.vician.net/tv.zip but you need to enable unknown sources and overriding system packages updates from unknown sources. And you would need to uninstall and remove it when the official update will be released.

The update has been released now.

**Comment by I-MacHunt** [comment] 2023-01-21 10:05
> Typical!! I finally got it working last night 😂😂😂

**Comment by DeHickok** [comment] 2023-01-21 12:48
> > You can use mine temporary fix zip on https://wiki.vician.net/tv.zip but you need to enable unknown sources and overriding system packages updates from unknown sources. And you would need to uninstall and remove it when the official update will be released.
> 
> The update has been released now.

but i still get same error: "module 'inspect' has no attribute 'getargspec'
Please try again." after reinstallation whole KODI and AddOn OneDrive (Android Sony TV)

**Comment by janglapuk** [comment] 2023-01-21 15:18
> but i still get same error: "module 'inspect' has no attribute 'getargspec' Please try again." after reinstallation whole KODI and AddOn OneDrive (Android Sony TV)

The main Kodi repository is still serving the old version. [Google Drive](https://kodi.tv/addons/nexus/plugin.googledrive) plugin still shows **1.4.10+matrix.2**, and [Cloud Drive Common Module](https://kodi.tv/addons/nexus/script.module.clouddrive.common) shows **1.3.9+matrix.2**, instead of the latest one.

I still don't know if the information hasn't been updated by the author, or there is a delay in getting it updated to the Kodi database.

This solution can solve this problem by following the instructions given in the [README.md](https://github.com/cguZZman/repository.plugins/blob/master/README.md) in this repository by installing using **repo.daro.mx** source and selecting the latest version of addons repository (select **repository.cguzzman-3.0.0.zip** for Nexus).

Make sure to enabling "**Unknown Source**" and change "**Update official add-ons from**" option to "**Any repositories**" placed in **Settings / System / Add-ons** setting before doing the instructions.

Or, you can look at this [screencast video](https://www.veed.io/view/0d01b09d-a0ab-496e-9ae7-ef38d6da84bf?panel=share) for how to do that.

**Comment by pikilon** [comment] 2023-01-21 18:59
thank you @janglapuk very useful.
Do you know how to donate to @cguZZman ?

**Comment by cguZZman** [comment] 2023-01-21 22:15
The new version has been submitted to the Kodi repository. It takes some time.

**Closed as completed by cguZZman** 2023-01-21 22:15 UTC

**Comment by ClassickTech** [comment] 2023-01-21 22:36
> The new version has been submitted to the Kodi repository. It takes some time.

Your update is Live. I just tried it and everything is back working again! Thanks!

**Comment by Makukorn** [comment] 2023-01-22 19:25
![IMG_20230122_132335](https://user-images.githubusercontent.com/84855594/213935837-d30652e6-2883-4fbd-b606-3b545c12921c.jpg)

I can't update to 1.5.0 from official repository. I'm getting this error.

Google TV on Hisense U8H

**Comment by I-MacHunt** [comment] 2023-01-22 19:47
Add http://repo.daro.mx as a source as per https://github.com/cguZZman/repository.plugins instructions and update it from there.

**Comment by Makukorn** [comment] 2023-01-22 21:12
> Add http://repo.daro.mx as a source as per https://github.com/cguZZman/repository.plugins instructions and update it from there.

Thats what i'm doing. Same error.

![IMG_20230122_151040](https://user-images.githubusercontent.com/84855594/213940662-a675975d-3f87-4403-9c5f-a08a95811ad1.jpg)
![IMG_20230122_151053](https://user-images.githubusercontent.com/84855594/213940666-10c84183-8573-46cc-8c18-a72c20806bc1.jpg)

Update: I was missing One config. I put The add ons update to any repo instead of only official and now it's working. 

Thx!

**Comment by I-MacHunt** [comment] 2023-01-22 21:16
Have you made sure to update all of the "dependencies"?

**Comment by PaulinHalenria** [comment] 2023-01-22 21:29
Hi

Got the same issue. Had to remove the old app first + all the dependencies
and settings.
Then add the 1.5.0 with success

Regards

**Comment by I-MacHunt** [comment] 2023-01-22 21:31
What hardware are you all using?

**Comment by PaulinHalenria** [comment] 2023-01-22 21:36
For me, nVidia Shield and Xiaomi MiBox

Le dim. 22 janv. 2023 à 22:31, I-MacHunt ***@***.***> a
écrit :

**Comment by I-MacHunt** [comment] 2023-01-22 21:38
Make sure to go into Nvidia settings/apps/kodi/permissions and allow access to files etc. ALWAYS not just "when using the app". That's what messed everything up for me.
