### ISSUE TITLE
Remove invalid characters in filenames when exporting

### ISSUE THREAD

**Issue by DaleHenry** [cguZZman/plugin.googledrive#130] opened 2020-03-17 21:27 UTC
So I am setting up a media center with kodi and all my files are in Google Drive. All files are present in a Shared Drive from an .edu account. So my problem is that I have around 415 movies in a folder "Movies" each in its separate folder named "MovieName(yyyy)". So when I am importing the "Movies" only around 290 of them gets imported as .strm files. I try to import the non added movies manually by selecting the particular movie folder and importing it, that still doesn't import the files. All I get is a message that says importing that disappears soon. I tried re-importing and it still imports the **same** movies. Hoping to receive a solution to this issue as soon as possible.
Thanks in advance.
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/4345906/kodi.log)

**Comment by cguZZman** [comment] 2020-03-18 21:46
Try to export only the movie or folder that was not exported and send me a debug log file of that.
Also make sure your target folder, where strm files will be created, is empty.

**Comment by DaleHenry** [comment] 2020-03-19 08:16
So I have created a "New Folder" and tried to export two of the non exported movies to that folder. Still they weren't exported. Attaching log of the same.
[kodi.log](https://github.com/cguZZman/plugin.googledrive/files/4353345/kodi.log)

**Comment by cguZZman** [comment] 2020-03-19 13:32
The problem is the name of your folder and files. They have invalid characters that Windows does not accept them. In this case is the colon punctuation. For example: `300: ....` or `2001: ....`

I will mark this a an future enhancement, where the addon can help removing these characters when exporting. But in the meantime you need to rename them. 
Here is a list of invalid characters, in case you want to check: https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3

**Comment by DaleHenry** [comment] 2020-03-19 17:22
Thank you for your help. I will probably move to Linux anyway to setup the media center. Did not expect it to be such a simple issue. Sorry to bother you for such issues. Thanks again

**Comment by cguZZman** [comment] 2020-10-11 22:38
after reviewing this issue seems to be a very rare and have decided to close it. 
Name should be fixed in the drive before exporting.

**Closed by cguZZman** 2020-10-11 22:38 UTC
Labels: enhancement

**Comment by pctechkid** [comment] 2020-12-16 19:08
Up. This issue still exists, is there any workaround other than naming the file in the drive before exporting? I feel like this is a critical bug especially for windows users.
