### ISSUE TITLE
on Firestick can see main folder, but not individual files

### ISSUE THREAD

**Issue by femaltez1** [cguZZman/plugin.googledrive#45] opened 2018-12-23 21:01 UTC
Using Google Drive, my account credentials work, and can see main folder and main directory of my files, but wont disply my individual files.  Please help.  thanks. Frank

**Comment by ericbreynaert** [comment] 2018-12-25 11:46
same problem in windows, 1.2.12

**Comment by cguZZman** [comment] 2019-02-21 19:37
Are you guys still having this issue? Please paste your debug log file

**Comment by femaltez1** [comment] 2019-02-22 14:56
still having the problem.  Will try to send log soon. thank you.

**Comment by PedroC1999** [comment] 2019-02-25 19:58
@cguZZman 

Attached is a log that has the issue in some folders, and not in some. At the end, I also successfully stream a video.

https://paste.kodi.tv/muveqecaga

Hope this is helpful, the error is very much intermittent, a restart normally fixes it, but it is random(ish)

**Comment by cguZZman** [comment] 2020-02-11 21:50
I tested it and was unable to reproduce. Will close it for now. If you still have the problem post your debug log file again and try to explain what you were doing or give more context when this happened.

**Closed by cguZZman** 2020-02-11 21:50 UTC
Labels: debug log required
