### ISSUE TITLE
Playback issue (freezing) : Kodi 19.3, NVIDIA Shield, Experience 9.0

### ISSUE THREAD

**Issue by tatoomana** [cguZZman/plugin.googledrive#277] opened 2022-01-14 08:50 UTC
Hello,

Since the Experience 9.0 update, video playback freezes after 5 to 15 seconds. No playing issue from an external USB hard drive.

Does anyone have the problem? 

Thanking you in advance.

**Comment by Rupash2005** [comment] 2022-01-16 15:30
Yes it happens for me to , have reinstalled KODI and google drive add on still no fix yet 

Waiting for the developer to fix this issue

**Comment by tatoomana** [comment] 2022-01-16 21:20
> Yes it happens for me to , have reinstalled KODI and google drive add on still no fix yet
> 
> Waiting for the developer to fix this issue

Thank you, I'm not alone !

**Comment by ghost** [comment] 2022-01-17 19:29
Same problem here. Not sure this is a shield issue only. I tried on a fresh Kodi install on a Windows machine and can't play any files more than a few seconds and only with the default skin. 
On the Shield I use the Amber skin and the the playback won't even start and stays on "loading". Same thing on the Windows machine after installing the Amber skin.

I've also tried to configure the addon to always ask to choose the stream before playback, and I sometimes get an error about "ASCII character" or similar. So far I cannot make it reproductible but will tried to get a log of it.

**Comment by Rupash2005** [comment] 2022-01-18 05:28
![image](https://user-images.githubusercontent.com/60261342/149875503-b7806f1f-2aab-41f9-9d9e-2fc0bbc0c2b5.png)

Glad im not alone on this case , Tried with Windows machine on windows 11 , kodi and google drive add on works great complete a movie on my windows machine 

Not sure only after i updated my shield experience  9.0 , Im experiencing this kind of issue on my device

im still confused weather the problm is on my shield (Android 11 ) or with the KODI / Google drive

**Comment by KinjigMedia** [comment] 2022-01-20 04:47
Same issue here with Nvidia Shield, caused immediately after I upgraded to Android 9.0.

Edit: Followed the steps mentioned by SCAPELLI in [#255](https://github.com/cguZZman/plugin.googledrive/issues/255). Worked like a charm! Thank you FQsqQ for mentioning it in this issue.

**Comment by ghost** [comment] 2022-01-21 19:42
The fix proposed by SCAPELLI in the issue pinned on the home page worked for me  (#255).

Just add the following lines in advancedsettings.xml :

```
<network>
<disablehttp2>true</disablehttp2> 
</network>
```

~~NB : since the update to Android 11, access to the Android/data/... folder is very restricted. Before that one could copy a advancedsettings.xml file to the kodi userdata directory from Total Commander or such file browser app, but now this folder is only accessible to the app itself, so you have to use kodi file explorer to copy the advancedsettings.xml files from a more open folder (typically the Download directory on the Shield).~~

Edit : I could write to the userdata folder with the X-Plore app available from the Shield Playstore

**Comment by Rupash2005** [comment] 2022-01-22 03:55
Hi just an update guys ! 

after disabling the disablehttp2 on advancedsettings.xml  and doing a complete restart
that fix my kodi and all back to normal with google drive add on

**Comment by mg1234567** [comment] 2022-02-15 03:37
https://github.com/cguZZman/plugin.googledrive/issues/273#issuecomment-1039819575

**Comment by cguZZman** [comment] 2023-01-21 22:37
Just closing all issues related with playback since the addon has nothing to do with it. Kodi is in charge of doing the playback. The addon's job is to pass the video to kodi to be played.
Start by disabling http2.

**Closed as completed by cguZZman** 2023-01-21 22:37 UTC
